resolver: lts-13.19

# packages: []


extra-deps:
  - cairo-0.13.6.0
  - gtk2hs-buildtools-0.13.5.0
  - SDL-0.6.7.0
  - SDL-gfx-0.7.0.0
  - SDL-image-0.6.2.0
  - SDL-ttf-0.6.3.0
  - unagi-chan-0.4.1.0


